name: Deploy to Preview Channel

on:
  pull_request:
    branches: [master]
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i -g yarn
      - run: yarn set version stable
      - run: yarn install --immutable
      - run: yarn run lint:fix
      - run: yarn run build
      # - run: npm ci && yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHOCOLATE_DEMO }}'
          expires: 30d
          projectId: chocolate-demo

